#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom404.html > /dev/null

# Configure Nginx to use the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        add_header Content-Type text/html;
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /custom404.html;
    location = /custom404.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Reload Nginx configuration
sudo nginx -s reload
