#!/bin/bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy to send traffic to web-01 and web-02 using roundrobin
echo "frontend web_front
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy service to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply the configuration
sudo service haproxy restart
