#!/usr/bin/env bash
# Update the Nginx configuration file to listen on port 80
sudo sed -i 's/ listen 80;/ listen 80 default_server;/g' /etc/nginx/sites-available/default
# Restart Nginx to apply the changes
sudo systemctl restart nginx
